mock_tweets = [
    {
        "text": "Sustainability is the key to our future! #Sustainability #EcoFriendly",
        "created_at": "2024-12-02T10:00:00Z",
        "user": "User1",
        "likes": 150,
        "retweets": 45,
    },
    {
        "text": "We need to do more to reduce our carbon footprint. #ClimateAction #Sustainability",
        "created_at": "2024-12-01T15:30:00Z",
        "user": "User2",
        "likes": 200,
        "retweets": 60,
    },
    {
        "text": "Eco-friendly living isn’t just a trend; it’s a necessity. #GoGreen #PlasticFree",
        "created_at": "2024-12-01T18:45:00Z",
        "user": "User3",
        "likes": 120,
        "retweets": 30,
    },
    {
        "text": "Renewable energy is cheaper and more sustainable. #RenewableEnergy #GreenEnergy",
        "created_at": "2024-12-02T08:15:00Z",
        "user": "User4",
        "likes": 175,
        "retweets": 50,
    },
    {
        "text": "Plastic-free July was a success! Let’s keep it going year-round. #PlasticFree",
        "created_at": "2024-11-30T14:20:00Z",
        "user": "User5",
        "likes": 80,
        "retweets": 20,
    },
    {
        "text": "Cutting down our carbon footprint one step at a time. #CarbonFootprint #ClimateChange",
        "created_at": "2024-12-01T12:00:00Z",
        "user": "User6",
        "likes": 300,
        "retweets": 90,
    },
    {
        "text": "Zero waste is not just a goal; it’s a lifestyle. #ZeroWaste #EcoFriendly",
        "created_at": "2024-12-01T10:30:00Z",
        "user": "User7",
        "likes": 100,
        "retweets": 25,
    },
    {
        "text": "Green living makes the world a better place. #GreenLiving",
        "created_at": "2024-12-01T16:45:00Z",
        "user": "User8",
        "likes": 95,
        "retweets": 40,
    },
    {
        "text": "Climate action is needed now more than ever. #ClimateAction",
        "created_at": "2024-12-02T11:00:00Z",
        "user": "User9",
        "likes": 210,
        "retweets": 75,
    },
    {
        "text": "Using renewable energy to power our homes is the future. #GreenEnergy #RenewableEnergy",
        "created_at": "2024-12-01T13:15:00Z",
        "user": "User10",
        "likes": 220,
        "retweets": 60,
    },
    # Edge case: No hashtags
    {
        "text": "I’m so proud of everyone taking steps towards a better planet.",
        "created_at": "2024-11-30T09:45:00Z",
        "user": "User11",
        "likes": 70,
        "retweets": 15,
    },
    # Edge case: Non-English text
    {
        "text": "La sostenibilidad es clave para el futuro. #Sostenibilidad #EcoFriendly",
        "created_at": "2024-12-02T14:30:00Z",
        "user": "User12",
        "likes": 60,
        "retweets": 20,
    },
]